<a href="https://colab.research.google.com/github/Anmolbhattara/Machine-Learning-Lab/blob/main/1BM23CS039_Lab_1_DataProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import fetch_california_housing
import pandas as pd

# Load dataset
housing_data = fetch_california_housing(as_frame=True)

# Convert to DataFrame
housing = housing_data.frame

# Add Ocean Proximity column (for lab requirement)
housing['ocean_proximity'] = 'NEAR OCEAN'

# Save as CSV
housing.to_csv("housing.csv", index=False)

housing.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal,ocean_proximity
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526,NEAR OCEAN
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585,NEAR OCEAN
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521,NEAR OCEAN
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413,NEAR OCEAN
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422,NEAR OCEAN

In [2]:
from sklearn.datasets import load_diabetes
import pandas as pd

# Load dataset
diabetes_data = load_diabetes(as_frame=True)

# Convert to DataFrame
diabetes = diabetes_data.frame

# Save as CSV
diabetes.to_csv("diabetes.csv", index=False)

diabetes.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [3]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = [
    "age", "workclass", "fnlwgt", "education", "education-num",
    "marital-status", "occupation", "relationship", "race", "sex",
    "capital-gain", "capital-loss", "hours-per-week", "native-country", "income"
]

adult = pd.read_csv(url, names=columns, sep=", ", engine="python")

adult.to_csv("adult.csv", index=False)

adult.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [4]:
from google.colab import files

files.download("housing.csv")
files.download("diabetes.csv")
files.download("adult.csv")

In [5]:
import pandas as pd

# Load dataset
housing = pd.read_csv("/content/housing.csv")

# Display first 5 rows
print("First 5 rows:")
display(housing.head())

# Display dataset information
print("\nDataset Information:")
housing.info()

# Display statistical summary
print("\nStatistical Summary:")
display(housing.describe())

# Count of unique labels in ocean_proximity
print("\nOcean Proximity Count:")
print(housing['ocean_proximity'].value_counts())

# Columns with missing values
print("\nColumns with Missing Values:")
print(housing.isnull().sum()[housing.isnull().sum() > 0])

First 5 rows:

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal,ocean_proximity
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526,NEAR OCEAN
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585,NEAR OCEAN
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521,NEAR OCEAN
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413,NEAR OCEAN
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422,NEAR OCEAN

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   MedInc           20640 non-null  float64
 1   HouseAge         20640 non-null  float64
 2   AveRooms         20640 non-null  float64
 3   AveBedrms        20640 non-null  float64
 4   Population       20640 non-null  float64
 5   AveOccup         20640 non-null  float64
 6   Latitude         20640 non-null  float64
 7   Longitude        20640 non-null  float64
 8   MedHouseVal      20640 non-null  float64
 9   ocean_proximity  20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

Statistical Summary:

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

Ocean Proximity Count:
ocean_proximity
NEAR OCEAN    20640
Name: count, dtype: int64

Columns with Missing Values:
Series([], dtype: int64)

In [6]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Load dataset
diabetes = pd.read_csv("/content/diabetes.csv")

# Display first 5 rows
print("First 5 rows:")
display(diabetes.head())

# Check missing values
print("\nMissing Values Before Handling:")
print(diabetes.isnull().sum())

# Handle missing values
diabetes.fillna(diabetes.mean(), inplace=True)

# Handle outliers using IQR
Q1 = diabetes.quantile(0.25)
Q3 = diabetes.quantile(0.75)
IQR = Q3 - Q1

diabetes = diabetes[~((diabetes < (Q1 - 1.5 * IQR)) |
                      (diabetes > (Q3 + 1.5 * IQR))).any(axis=1)]

# Min-Max Scaling
minmax = MinMaxScaler()
diabetes_minmax = minmax.fit_transform(diabetes)

# Standard Scaling
standard = StandardScaler()
diabetes_standard = standard.fit_transform(diabetes)

print("\nDiabetes Dataset Shape After Preprocessing:")
print(diabetes.shape)

First 5 rows:

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

Missing Values Before Handling:
age       0
sex       0
bmi       0
bp        0
s1        0
s2        0
s3        0
s4        0
s5        0
s6        0
target    0
dtype: int64

Diabetes Dataset Shape After Preprocessing:
(409, 11)

In [7]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load dataset
adult = pd.read_csv("/content/adult.csv")

# Display first 5 rows
print("First 5 rows:")
display(adult.head())

# Check missing values
print("\nMissing Values Before Handling:")
print(adult.isnull().sum())

# Handle missing values
adult.replace('?', np.nan, inplace=True)
adult.fillna(adult.mode().iloc[0], inplace=True)

# Identify categorical columns
categorical_cols = adult.select_dtypes(include='object').columns
print("\nCategorical Columns:")
print(categorical_cols)

# Encode categorical columns
le = LabelEncoder()
for col in categorical_cols:
    adult[col] = le.fit_transform(adult[col])

# Standard Scaling
scaler = StandardScaler()
adult_scaled = scaler.fit_transform(adult)

print("\nAdult Dataset Shape After Preprocessing:")
print(adult.shape)

First 5 rows:

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

Missing Values Before Handling:
age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

Categorical Columns:
Index(['workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'sex', 'native-country', 'income'],
      dtype='object')

Adult Dataset Shape After Preprocessing:
(32561, 15)